spring:
  application:
    name: audition-api
  config:
    import: "optional:configserver:"
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    throw-exception-if-no-handler-found: true
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 9090
  max-http-request-header-size: 16KB
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: 'info,health'
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
audition-integration-api:
  base-url: https://jsonplaceholder.typicode.com
  get-posts-path: /posts
  get-single-post-path: /posts/%s
  get-post-comments-path: /posts/%s/comments
  get-comments-by-post: /comments?postId=%s
app:
  date-format: yyyy-MM-dd
  locale: en_US
